### ISSUE TITLE
Donkey Kong hangs after first gamepad input

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/gw-libretro#45]
this is the offending commit, it seems:
https://github.com/libretro/gw-libretro/commit/342342580027d276062058fb9bc9d8ec1c28216f
Unfortunately, it's a big one.

EDIT: it seems you can move, just not jump around, which seems to maybe be related to changes in input indexing.

**Comment by wvalcke** [comment]
I have seen this behavior as well, but with the latest version i do not have this problem anymore. 
Andre will probably make a new release in the near future which fixes some crashes of the core. Let's wait for this, then you should be able to play the game again.

**Comment by leiradel** [comment]
This is likely fixed in https://github.com/libretro/gw-libretro/commit/9a924cea028f17d3be3499f1530abc14d9071983

Can you confirm? Thanks

**Comment by DeclanGreen** [comment]
Aww, and I loved this game.

**Comment by mat231228** [comment]
Hi André,
It seems this issue or a similar one is still present.
I'm running gw-libretro on a Raspberry Pi 3 with RetroPie (installed RetroPie *lr-gw* package from source, which pulls the latest master from github).
When trying to run [DonkeyKong](https://bot.libretro.com/assets/cores/Handheld%20Electronic%20Game/Donkey%20Kong%20%28Nintendo%2C%20Multi%20Screen%29.zip), the game freezes as soon as either Game A or Game B is selected and the log shows the following:
```
[libretro ERROR]
==============================
[string "main.lua"]:72: bad argument #1 to 'pairs' (table expected, got boolean)
stack traceback:
        [C]: in function 'pairs'
        [string "main.lua"]:72: in function <[string "main.lua"]:66>
```
Before entering Game A or Game B, both the directional pad and jump button animate when pressed.

When trying to run [DonkeyKong II](https://bot.libretro.com/assets/cores/Handheld%20Electronic%20Game/Donkey%20Kong%20II%20%28Nintendo%2C%20Multi%20Screen%29.zip), as soon as the directional pad is pressed the game freezes, independent of game A or game B selection. I get the following log, where only the line numbers are different:
```
[libretro ERROR]
==============================
[string "main.lua"]:77: bad argument #1 to 'pairs' (table expected, got boolean)
stack traceback:
        [C]: in function 'pairs'
        [string "main.lua"]:77: in function <[string "main.lua"]:71>
```

Thanks!

**Comment by leiradel** [comment]
I can see why the error happens, I'll try a fix soon. Thanks for the report.

**Comment by leiradel** [comment]
@mat231228 I've updated both games [here](https://bot.libretro.com/assets/cores/Handheld%20Electronic%20Game/) and they seem to be working now. Can you try them and let me know?

Thanks.

**Comment by mat231228** [comment]
Yes! Both working perfectly now, on both retropie and retroarch on android!

Thank you so much! :-)

**Comment by leiradel** [comment]
Great, I'm closing this issue then.
